# Generated by Django 5.2.10 on 2026-01-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watersector',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='watersector',
            name='threshold',
            field=models.FloatField(default=5000.0),
        ),
    ]
