# Generated by Django 5.2.10 on 2026-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_monitor', '0002_remove_watersector_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersector',
            name='inflow_liters',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watersector',
            name='ph_level',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='watersector',
            name='pressure_bar',
            field=models.FloatField(default=3.5),
        ),
    ]
